### ISSUE TITLE
zenfs编译错误请教

### ISSUE THREAD

**Issue by YummuyWang** [ywang-wnlo/ywang-wnlo.github.io#39]
在这一步遇到了如下错误，
Build and install rocksdb with zenfs enabled:
DEBUG_LEVEL=0 ROCKSDB_PLUGINS=zenfs make -j48 db_bench install

目测是缺少函数定义，在ide中也不能跳转，undefined reference to `rocksdb::SstPartitionerFactory::CreateFromString(rocksdb::ConfigOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<rocksdb::SstPartitionerFactory>*)'
我在options_type.h中加入了#include "rocksdb/sst_partitioner.h"编译通过了
但是在 plugin/zenfs/util下make还是会报错
undefined reference to `rocksdb::SstPartitionerFactory::CreateFromString(rocksdb::ConfigOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<rocksdb::SstPartitionerFactory>*)'
能顺便留个联系方式吗

	install -d //usr/local/$header_dir; \
done
for header in `find "include/rocksdb" -type f -name *.h`; do \
	install -C -m 644 $header //usr/local/$header; \
done
for header in   plugin/zenfs/fs/fs_zenfs.h  plugin/zenfs/fs/zbd_zenfs.h  plugin/zenfs/fs/io_zenfs.h  plugin/zenfs/fs/version.h  plugin/zenfs/fs/metrics.h  plugin/zenfs/fs/snapshot.h  plugin/zenfs/fs/filesystem_utility.h  plugin/zenfs/fs/zonefs_zenfs.h  plugin/zenfs/fs/zbdlib_zenfs.h; do \
	install -d //usr/local/include/rocksdb/`dirname $header`; \
	install -C -m 644 $header //usr/local/include/rocksdb/$header; \
done
install -C -m 644 rocksdb.pc /usr/local/lib/pkgconfig/rocksdb.pc
install -d /usr/local/lib
install -C -m 755 librocksdb.a /usr/local/lib
[ -e librocksdb.so.8.4.0 ] && make install-shared || :
/usr/bin/ld: ./librocksdb.a(cf_options.o): in function `rocksdb::OptionTypeInfo::AsCustomSharedPtr<rocksdb::SstPartitionerFactory>(int, rocksdb::OptionVerificationType, rocksdb::OptionTypeFlags)::{lambda(rocksdb::ConfigOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*)#1}::operator()(rocksdb::ConfigOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*) const':
/home/spdk/Desktop/rocksdb/./include/rocksdb/utilities/options_type.h:495: undefined reference to `rocksdb::SstPartitionerFactory::CreateFromString(rocksdb::ConfigOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<rocksdb::SstPartitionerFactory>*)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1308: db_bench] Error 1

**Comment by YummuyWang** [comment]
在options_type.h中添加#include "rocksdb/sst_partitioner.h"后能编译但是进入 plugin/zenfs/util目录后不能make
还是报错
/home/spdk/Desktop/rocksdb/./include/rocksdb/utilities/options_type.h:495: undefined reference to `rocksdb::SstPartitionerFactory::CreateFromString(rocksdb::ConfigOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<rocksdb::SstPartitionerFactory>*)'

**Comment by ywang-wnlo** [comment]
首先我没出现过这个错误，所以可能帮不上
不过你可以试试全 `make clean` 之后，严格按照 `https://github.com/westerndigitalcorporation/zenfs` 的 README 指示操作（例如：不要忘记 `libzbd` 以及其他包的准备）

**Comment by YummuyWang** [comment]
可能是编译的问题，我make不使用多线程就不会报这个错了
